### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by gabrielmll** [SandroMiccoli/UFMGAberta#1]
Um código de zoom com tipsy: http://bl.ocks.org/Matthew-Weber/5484861

Irei compreender o código, acredito que ajudará.

**Comment by gabrielmll** [comment]
http://stackoverflow.com/questions/14697232/how-do-i-show-a-bootstrap-tooltip-with-an-svg-object

**Comment by gabrielmll** [comment]
ahá... jQuery não funciona bem com SVG.

Eis a esperança: https://github.com/shawnbot/d3-bootstrap
"
Twitter's Bootstrap is an awesome CSS framework with some really nice JavaScript tools. The problem with these tools, though, is that they rely heavily on jQuery, while d3 provides (approximately) 99% of the functionality they require.
"

**Comment by SandroMiccoli** [comment]
Resolvido utilizando tipsy.js: http://onehackoranother.com/projects/jquery/tipsy/
